### ISSUE TITLE
Add cell list to simple bond calculation

### ISSUE THREAD

**Issue by merrygoat** [royallgroup/TCC#29]
To speed up determination of simple (non-voronoi) bond lengths. Add a cell list.

**Comment by tranqui** [comment]
Was this resolved @merrygoat? The comments above indicate it was fixed, but then it was reopened?

**Comment by merrygoat** [comment]
I closed it by accident I think, It is not yet resolved. This requires refactoring of some of the more complex clusters which is quite a big job.
